# Generated by Django 6.1 on 2026-09-04 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('MEDICINE', 'Medicine'), ('EQUIPMENT', 'Equipment')], max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('AVAILABLE_EQUIPMENT', 'Available Equipment'), ('UNAVAILABLE_EQUIPMENT', 'Unavailable Equipment')], max_length=30)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='facilities.facility')),
            ],
        ),
    ]
