# Generated by Django 6.1 on 2026-09-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
