# Generated by Django 6.1 on 2026-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_doctor_alter_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='triage_bypass_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='triage_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='triage_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
