# Generated by Django 6.1 on 2026-08-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('HEALTH_WORKER', 'Health Worker'), ('PATIENT', 'Patient')], max_length=20),
        ),
    ]
